"""
Report generation module for scan results.
"""

import json
from datetime import datetime
from typing import Dict


class ReportGenerator:
    """Generate reports from scan results."""
    
    def generate(self, scan: Dict, format: str = 'json') -> str:
        """
        Generate a report from scan data.
        
        Args:
            scan: Scan data dictionary
            format: Output format ('json', 'html', 'text')
            
        Returns:
            Formatted report string
        """
        if format == 'json':
            return self._generate_json(scan)
        elif format == 'html':
            return self._generate_html(scan)
        elif format == 'text':
            return self._generate_text(scan)
        else:
            raise ValueError(f"Unknown format: {format}")
    
    def _generate_json(self, scan: Dict) -> str:
        """Generate JSON report."""
        report = {
            'scan_id': scan['id'],
            'target': scan['target'],
            'timestamp': scan['created_at'],
            'hosts': scan['results'].get('hosts', []),
            'summary': {
                'total_hosts': len(scan['results'].get('hosts', [])),
                'total_services': sum(
                    len(h.get('services', []))
                    for h in scan['results'].get('hosts', [])
                ),
            }
        }
        return json.dumps(report, indent=2)
    
    def _generate_html(self, scan: Dict) -> str:
        """Generate HTML report."""
        hosts = scan['results'].get('hosts', [])
        total_services = sum(len(h.get('services', [])) for h in hosts)
        
        html = f"""
<!DOCTYPE html>
<html>
<head>
    <title>VulnScanCLI Scan Report - {scan['target']}</title>
    <style>
        body {{ font-family: Arial, sans-serif; margin: 20px; }}
        h1 {{ color: #333; }}
        .summary {{ background: #f0f0f0; padding: 10px; border-radius: 5px; }}
        .host {{ margin: 20px 0; padding: 10px; border: 1px solid #ddd; }}
        .service {{ margin: 5px 0; padding: 5px; background: #fafafa; }}
        .critical {{ color: red; font-weight: bold; }}
        .high {{ color: orange; font-weight: bold; }}
        .medium {{ color: #ff9800; }}
        .low {{ color: green; }}
    </style>
</head>
<body>
    <h1>VulnScanCLI Scan Report</h1>
    <p><strong>Target:</strong> {scan['target']}</p>
    <p><strong>Date:</strong> {scan['created_at']}</p>
    
    <div class="summary">
        <h2>Summary</h2>
        <p>Total hosts: {len(hosts)}</p>
        <p>Total services: {total_services}</p>
    </div>
    
    <h2>Hosts</h2>
"""
        
        for host in hosts:
            html += f"""
    <div class="host">
        <h3>{host['ip']} - {host['hostname']}</h3>
        <p>Status: {host['state']}</p>
"""
            
            if host.get('services'):
                html += "        <h4>Services:</h4>\n"
                for service in host['services']:
                    html += f"""        <div class="service">
            Port {service['port']}: {service['service']} ({service['version']})
        </div>\n"""
            
            html += "    </div>\n"
        
        html += """
</body>
</html>
"""
        return html
    
    def _generate_text(self, scan: Dict) -> str:
        """Generate plain text report."""
        hosts = scan['results'].get('hosts', [])
        total_services = sum(len(h.get('services', [])) for h in hosts)
        
        text = f"""
╔════════════════════════════════════════════════════════════════╗
║                   VulnScanCLI SCAN REPORT                      ║
╚════════════════════════════════════════════════════════════════╝

Scan ID:        {scan['id']}
Target:         {scan['target']}
Date:           {scan['created_at']}
Status:         {scan['status']}

SUMMARY
───────────────────────────────────────────────────────────────
Total Hosts:    {len(hosts)}
Total Services: {total_services}

HOSTS DISCOVERED
───────────────────────────────────────────────────────────────
"""
        
        for host in hosts:
            text += f"\n{host['ip']} ({host['hostname']}) - {host['state']}\n"
            
            if host.get('services'):
                text += "  Services:\n"
                for service in host['services']:
                    text += f"    • Port {service['port']}: {service['service']} v{service['version']}\n"
            else:
                text += "  No services detected\n"
        
        text += "\n" + "═" * 60 + "\n"
        text += "Report generated by VulnScanCLI\n"
        
        return text
